sudo: required
services:
  - docker

before_install:
  - docker build -t s9c9t9/docker-react -f Dockerfile.dev .

script: # how to run test suite
  - docker run s9c9t9/docker-react npm run test -- --coverage