sudo: required
services:
  - docker

before_install:
  - docker build -t s9c9t9/docker-react -f Dockerfile.dev .

script: # how to run test suite
  - docker run s9c9t9/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2" # depends on the geographic region where the app is stored 
  app: "docker"
  env: "Docker-env" # given in aws project page
  bucket_name: "asdasd-asf-asdas-d" # a place in aws where the project files will be stored auto-created
  bucket_path: "docker"
  on:
    branch: master # deploy when code is pushed to the master branch  
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"